### ISSUE TITLE
Mimetypes to render to conform with notebook

### ISSUE THREAD

**Issue by rgbkrk** [nteract/transformime-jupyter-transformers#2]
* [x] `application/javascript`
* [X] `text/html` - Note: needs to handle scripts, comes from transformime
* [X] `text/markdown` - [Commonmark implementation](https://github.com/nteract/transformime-commonmark)
* [x] `text/latex` - Separate from transformime (https://github.com/nteract/transformime-jupyter-transformers/pull/4)
* [x] `image/svg+xml`
* [X] `image/png` - in transformime
* [X] `image/jpeg` - in transformime
* [X] `application/pdf`- original link implementation in #5, may want to try PDF.js later (likely separate repo)
* [X] `text/plain` - in transformime

**Comment by rgbkrk** [comment]
Should we migrate ConsoleTextRenderer from transformime-jupyter-transformers to transformime (?)

Actually, shouldn't the text/plain type handle ANSI codes too anyway?

**Comment by jdfreder** [comment]
I think text/plain =/= text/plain+ansi .

**Comment by rgbkrk** [comment]
We have these types of plainish output in Jupyter right?

* stdout, stderr (should absolutely respect emoji, character codes, color codes, etc.)
* text/plain (default output, strings, etc.)

All of these should end up in `pre`s I assume. What does our current text/plain do?

**Comment by rgbkrk** [comment]
I guess with your above suggestion, stdout/stderr are `text/plain+ansi`

**Comment by jdfreder** [comment]
Yeah that's what I'm thinking.  I don't recall if that's a real or valid mimetype though...  I should probably review how to use the `+`.

**Comment by rgbkrk** [comment]
I think conformance with the notebook is \#1 priority here.

**Comment by jdfreder** [comment]
`\#1` ;)

**Comment by jdfreder** [comment]
I feel silly, didn't realize the was the "jupyter" specific repo.  Ok, yes text/plain is a-okay to me.

**Comment by rgbkrk** [comment]
Since you're grabbing JS and SVG Jon, I'll tackle the current version of the PDF renderer. Oh but guh... It does linking and I'm not sure what that's like for Atom or Electron. Only makes sense in the server side notebook. :unamused:

**Comment by rgbkrk** [comment]
Finished off JS and SVG in #9

**Comment by rgbkrk** [comment]
The remaining one is proper script running for `text/html`.
